version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres      # Имя БД
      POSTGRES_USER: postgres   # Логин
      POSTGRES_PASSWORD: recursia2005 # Пароль
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: recursia2005
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: