version: '3.8'

services:
  postgres:  # Этот сервис будет использоваться ТОЛЬКО с профилем 'docker'
    image: postgres:15
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  app:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: local  # Автоматически активируем профиль 'docker'
      # Переопределяем настройки при необходимости:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/test
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: